# Generated by Django 3.0 on 2020-04-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcaje', '0006_auto_20200418_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcaje',
            old_name='hora',
            new_name='entrada',
        ),
        migrations.AddField(
            model_name='marcaje',
            name='salida',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
