# Generated by Django 3.0 on 2020-04-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marcaje', '0007_auto_20200418_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcaje',
            name='tipo',
        ),
    ]
