# Generated by Django 3.0 on 2020-04-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcaje', '0005_auto_20200305_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcaje',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='marcaje',
            name='usuario',
            field=models.CharField(default='00:00:00', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
